/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đổi mật khẩu của chính mình */
    post: operations["auth_change_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đăng nhập bằng email và mật khẩu */
    post: operations["auth_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đăng xuất */
    post: operations["auth_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Làm mới phiên đăng nhập (xoay vòng refresh token) */
    post: operations["auth_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Danh sách nhân viên (tìm, lọc, phân trang) */
    get: operations["employees_list"];
    put?: never;
    /** Thêm nhân viên (mật khẩu tạm hiện một lần) */
    post: operations["employees_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chi tiết nhân viên */
    get: operations["employees_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sửa thông tin nhân viên */
    patch: operations["employees_update"];
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mở khoá tài khoản */
    post: operations["employees_activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Khoá tài khoản (đăng xuất khỏi mọi thiết bị) */
    post: operations["employees_deactivate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cấp lại mật khẩu (mật khẩu tạm hiện một lần) */
    post: operations["employees_reset_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đặt vai trò */
    post: operations["employees_set_roles"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Kiểm tra tình trạng dịch vụ và cơ sở dữ liệu */
    get: operations["system_health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Thông tin, vai trò, quyền và bộ đếm của người đang đăng nhập */
    get: operations["me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** EmployeeCreate */
    EmployeeCreate: {
      /**
       * Department
       * @enum {string}
       */
      department: "MANAGEMENT" | "SALES" | "TECHNICAL";
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /** Phone */
      phone?: string | null;
      /** Roles */
      roles: ("MANAGER" | "SALE" | "TECH_LEAD" | "TECHNICIAN")[];
      /** Title */
      title?: string | null;
    };
    /** EmployeeOut */
    EmployeeOut: {
      /** Code */
      code: string;
      /** Department */
      department: string;
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Active */
      is_active: boolean;
      /** Is Locked */
      is_locked: boolean;
      /** Must Change Password */
      must_change_password: boolean;
      /** Phone */
      phone: string | null;
      /** Roles */
      roles: string[];
      /** Title */
      title: string | null;
      /** Version */
      version: number;
    };
    /** EmployeePage */
    EmployeePage: {
      /** Items */
      items: components["schemas"]["EmployeeOut"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** EmployeeSummary */
    EmployeeSummary: {
      /** Code */
      code: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Roles */
      roles: string[];
    };
    /** EmployeeUpdate */
    EmployeeUpdate: {
      /** Department */
      department?: ("MANAGEMENT" | "SALES" | "TECHNICAL") | null;
      /** Email */
      email?: string | null;
      /** Full Name */
      full_name?: string | null;
      /** Phone */
      phone?: string | null;
      /** Title */
      title?: string | null;
      /** Version */
      version: number;
    };
    /** EmployeeWithPassword */
    EmployeeWithPassword: {
      employee: components["schemas"]["EmployeeOut"];
      /** Temporary Password */
      temporary_password: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Database
       * @constant
       */
      database: "ok";
      /**
       * Status
       * @constant
       */
      status: "ok";
      /** Version */
      version: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginResponse */
    LoginResponse: {
      employee: components["schemas"]["EmployeeSummary"];
      /** Must Change Password */
      must_change_password: boolean;
    };
    /** MeEmployee */
    MeEmployee: {
      /** Code */
      code: string;
      /** Department */
      department: string;
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string | null;
    };
    /** MeResponse */
    MeResponse: {
      /** Capabilities */
      capabilities: {
        [key: string]: string[];
      };
      /** Counters */
      counters: {
        [key: string]: number;
      };
      employee: components["schemas"]["MeEmployee"];
      /** Roles */
      roles: string[];
    };
    /** RolesRequest */
    RolesRequest: {
      /** Roles */
      roles: ("MANAGER" | "SALE" | "TECH_LEAD" | "TECHNICIAN")[];
      /** Version */
      version: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VersionRequest */
    VersionRequest: {
      /** Version */
      version: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_change_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — UNAUTHENTICATED: Vui lòng đăng nhập. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — VALIDATION_ERROR (current_password / new_password) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — ACCOUNT_LOCKED: Tài khoản tạm khoá do đăng nhập sai nhiều lần. Vui lòng thử lại sau 15 phút. */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description problem+json — INVALID_CREDENTIALS: Email hoặc mật khẩu không đúng. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — ACCOUNT_DISABLED: Tài khoản đã bị vô hiệu hoá. Vui lòng liên hệ quản lý. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description problem+json — ACCOUNT_LOCKED: Tài khoản tạm khoá do đăng nhập sai nhiều lần. Vui lòng thử lại sau 15 phút. */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description problem+json — UNAUTHENTICATED: Vui lòng đăng nhập. | SESSION_REVOKED: Phiên đăng nhập đã bị thu hồi. Vui lòng đăng nhập lại. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  employees_list: {
    parameters: {
      query?: {
        q?: string | null;
        role?: ("MANAGER" | "SALE" | "TECH_LEAD" | "TECHNICIAN") | null;
        is_active?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeWithPassword"];
        };
      };
      /** @description problem+json — CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_activate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_reset_password: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeWithPassword"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_set_roles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RolesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  system_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Database unreachable (problem+json, code SERVICE_UNAVAILABLE) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description problem+json — UNAUTHENTICATED: Vui lòng đăng nhập. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — PASSWORD_CHANGE_REQUIRED | FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
