/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/attachments/{attachment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tải tệp đính kèm (ảnh sản phẩm) */
    get: operations["attachments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Nhật ký hệ thống (lọc theo thực thể / người thực hiện / khoảng ngày) */
    get: operations["audit_events_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đổi mật khẩu của chính mình */
    post: operations["auth_change_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đăng nhập bằng email và mật khẩu */
    post: operations["auth_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đăng xuất */
    post: operations["auth_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Làm mới phiên đăng nhập (xoay vòng refresh token) */
    post: operations["auth_refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Danh sách nhân viên (tìm, lọc, phân trang) */
    get: operations["employees_list"];
    put?: never;
    /** Thêm nhân viên (mật khẩu tạm hiện một lần) */
    post: operations["employees_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chi tiết nhân viên */
    get: operations["employees_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sửa thông tin nhân viên */
    patch: operations["employees_update"];
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mở khoá tài khoản */
    post: operations["employees_activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Khoá tài khoản (đăng xuất khỏi mọi thiết bị) */
    post: operations["employees_deactivate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cấp lại mật khẩu (mật khẩu tạm hiện một lần) */
    post: operations["employees_reset_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/employees/{employee_id}/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Đặt vai trò */
    post: operations["employees_set_roles"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Kiểm tra tình trạng dịch vụ và cơ sở dữ liệu */
    get: operations["system_health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Thông tin, vai trò, quyền và bộ đếm của người đang đăng nhập */
    get: operations["me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Danh sách sản phẩm (tìm, lọc, phân trang) */
    get: operations["products_list"];
    put?: never;
    /** Thêm sản phẩm */
    post: operations["products_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/import/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Xác nhận import sản phẩm từ CSV */
    post: operations["products_import_commit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/import/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Xem trước import sản phẩm từ CSV */
    post: operations["products_import_preview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chi tiết sản phẩm */
    get: operations["products_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sửa thông tin sản phẩm */
    patch: operations["products_update"];
    trace?: never;
  };
  "/api/v1/products/{product_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mở lại kinh doanh */
    post: operations["products_activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ngừng kinh doanh */
    post: operations["products_deactivate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{product_id}/image": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tải ảnh sản phẩm */
    post: operations["products_upload_image"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Danh sách dịch vụ (tìm, lọc, phân trang) */
    get: operations["services_list"];
    put?: never;
    /** Thêm dịch vụ */
    post: operations["services_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services/import/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Xác nhận import dịch vụ từ CSV */
    post: operations["services_import_commit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services/import/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Xem trước import dịch vụ từ CSV */
    post: operations["services_import_preview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services/{service_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chi tiết dịch vụ */
    get: operations["services_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Sửa thông tin dịch vụ */
    patch: operations["services_update"];
    trace?: never;
  };
  "/api/v1/services/{service_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mở lại kinh doanh */
    post: operations["services_activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/services/{service_id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ngừng kinh doanh */
    post: operations["services_deactivate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActorSummary */
    ActorSummary: {
      /** Code */
      code: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** AuditEventOut */
    AuditEventOut: {
      /** Action */
      action: string;
      actor: components["schemas"]["ActorSummary"] | null;
      /** Data */
      data: {
        [key: string]: unknown;
      } | null;
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      /** Entity Type */
      entity_type: string;
      /** From Status */
      from_status: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** To Status */
      to_status: string | null;
    };
    /** AuditEventPage */
    AuditEventPage: {
      /** Items */
      items: components["schemas"]["AuditEventOut"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Body_products_import_commit */
    Body_products_import_commit: {
      /** File */
      file: string;
    };
    /** Body_products_import_preview */
    Body_products_import_preview: {
      /** File */
      file: string;
    };
    /** Body_products_upload_image */
    Body_products_upload_image: {
      /** File */
      file: string;
    };
    /** Body_services_import_commit */
    Body_services_import_commit: {
      /** File */
      file: string;
    };
    /** Body_services_import_preview */
    Body_services_import_preview: {
      /** File */
      file: string;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** EmployeeCreate */
    EmployeeCreate: {
      /**
       * Department
       * @enum {string}
       */
      department: "MANAGEMENT" | "SALES" | "TECHNICAL";
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /** Phone */
      phone?: string | null;
      /** Roles */
      roles: ("MANAGER" | "SALE" | "TECH_LEAD" | "TECHNICIAN")[];
      /** Title */
      title?: string | null;
    };
    /** EmployeeOut */
    EmployeeOut: {
      /** Code */
      code: string;
      /** Department */
      department: string;
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Active */
      is_active: boolean;
      /** Is Locked */
      is_locked: boolean;
      /** Must Change Password */
      must_change_password: boolean;
      /** Phone */
      phone: string | null;
      /** Roles */
      roles: string[];
      /** Title */
      title: string | null;
      /** Version */
      version: number;
    };
    /** EmployeePage */
    EmployeePage: {
      /** Items */
      items: components["schemas"]["EmployeeOut"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** EmployeeSummary */
    EmployeeSummary: {
      /** Code */
      code: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Roles */
      roles: string[];
    };
    /** EmployeeUpdate */
    EmployeeUpdate: {
      /** Department */
      department?: ("MANAGEMENT" | "SALES" | "TECHNICAL") | null;
      /** Email */
      email?: string | null;
      /** Full Name */
      full_name?: string | null;
      /** Phone */
      phone?: string | null;
      /** Title */
      title?: string | null;
      /** Version */
      version: number;
    };
    /** EmployeeWithPassword */
    EmployeeWithPassword: {
      employee: components["schemas"]["EmployeeOut"];
      /** Temporary Password */
      temporary_password: string;
    };
    /**
     * EntityType
     * @enum {string}
     */
    EntityType: "EMPLOYEE" | "PRODUCT" | "SERVICE";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Database
       * @constant
       */
      database: "ok";
      /**
       * Status
       * @constant
       */
      status: "ok";
      /** Version */
      version: string;
    };
    /** ImageUploaded */
    ImageUploaded: {
      /**
       * Image Attachment Id
       * Format: uuid
       */
      image_attachment_id: string;
    };
    /** ImportCommitResult */
    ImportCommitResult: {
      /** Created */
      created: number;
    };
    /** ImportPreview */
    ImportPreview: {
      /** Invalid Count */
      invalid_count: number;
      /** Rows */
      rows: components["schemas"]["ImportRow"][];
      /** Total */
      total: number;
      /** Valid Count */
      valid_count: number;
    };
    /** ImportRow */
    ImportRow: {
      /** Data */
      data: {
        [key: string]: unknown;
      };
      /** Errors */
      errors: components["schemas"]["ImportRowError"][] | null;
      /** Line */
      line: number;
    };
    /** ImportRowError */
    ImportRowError: {
      /** Code */
      code: string;
      /** Field */
      field: string;
      /** Message */
      message: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginResponse */
    LoginResponse: {
      employee: components["schemas"]["EmployeeSummary"];
      /** Must Change Password */
      must_change_password: boolean;
    };
    /** MeEmployee */
    MeEmployee: {
      /** Code */
      code: string;
      /** Department */
      department: string;
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string | null;
    };
    /** MeResponse */
    MeResponse: {
      /** Capabilities */
      capabilities: {
        [key: string]: string[];
      };
      /** Counters */
      counters: {
        [key: string]: number;
      };
      employee: components["schemas"]["MeEmployee"];
      /** Roles */
      roles: string[];
    };
    /** ProductCreate */
    ProductCreate: {
      /** Brand */
      brand?: string | null;
      /**
       * Category
       * @enum {string}
       */
      category:
        | "PC"
        | "LAPTOP"
        | "MONITOR"
        | "PRINTER"
        | "SCANNER"
        | "PRINTER_SUPPLY"
        | "CAMERA"
        | "RECORDER"
        | "STORAGE"
        | "NETWORK"
        | "ACCESSORY"
        | "MATERIAL"
        | "SOFTWARE"
        | "OTHER";
      /** Name */
      name: string;
      /** Price */
      price: number;
      /**
       * Price Fixed
       * @default false
       */
      price_fixed: boolean;
      /** Sku */
      sku: string;
      /** Specs */
      specs?: string | null;
      /**
       * Unit
       * @enum {string}
       */
      unit: "CAI" | "MAY" | "BO" | "MET" | "CUON" | "HOP" | "LICENSE";
      /**
       * Vat Rate
       * @default 8
       */
      vat_rate: number | string;
      /** Warranty Months */
      warranty_months?: number | null;
    };
    /** ProductOut */
    ProductOut: {
      /** Brand */
      brand: string | null;
      /** Category */
      category: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Attachment Id */
      image_attachment_id: string | null;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name: string;
      /** Price */
      price: number;
      /** Price Fixed */
      price_fixed: boolean;
      /** Sku */
      sku: string;
      /** Specs */
      specs: string | null;
      /** Unit */
      unit: string;
      /** Vat Rate */
      vat_rate: string;
      /** Version */
      version: number;
      /** Warranty Months */
      warranty_months: number | null;
    };
    /** ProductPage */
    ProductPage: {
      /** Items */
      items: components["schemas"]["ProductOut"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ProductUpdate */
    ProductUpdate: {
      /** Brand */
      brand?: string | null;
      /** Name */
      name?: string | null;
      /** Price */
      price?: number | null;
      /** Price Fixed */
      price_fixed?: boolean | null;
      /** Specs */
      specs?: string | null;
      /** Vat Rate */
      vat_rate?: number | string | null;
      /** Version */
      version: number;
      /** Warranty Months */
      warranty_months?: number | null;
    };
    /** RolesRequest */
    RolesRequest: {
      /** Roles */
      roles: ("MANAGER" | "SALE" | "TECH_LEAD" | "TECHNICIAN")[];
      /** Version */
      version: number;
    };
    /** ServiceCreate */
    ServiceCreate: {
      /**
       * Category
       * @enum {string}
       */
      category:
        | "INSTALLATION"
        | "REPAIR"
        | "MAINTENANCE"
        | "REFILL"
        | "SOFTWARE"
        | "NETWORK_CABLING"
        | "OTHER";
      /** Code */
      code: string;
      /** Default Estimated Hours */
      default_estimated_hours?: number | string | null;
      /** Description */
      description?: string | null;
      /** Name */
      name: string;
      /** Price */
      price: number;
      /**
       * Price Fixed
       * @default false
       */
      price_fixed: boolean;
      /**
       * Unit
       * @enum {string}
       */
      unit: "CAI" | "MAY" | "BO" | "MET" | "CUON" | "HOP" | "LICENSE" | "LAN" | "DIEM" | "GIO";
      /**
       * Vat Rate
       * @default 8
       */
      vat_rate: number | string;
    };
    /** ServiceOut */
    ServiceOut: {
      /** Category */
      category: string;
      /** Code */
      code: string;
      /** Default Estimated Hours */
      default_estimated_hours: string | null;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name: string;
      /** Price */
      price: number;
      /** Price Fixed */
      price_fixed: boolean;
      /** Unit */
      unit: string;
      /** Vat Rate */
      vat_rate: string;
      /** Version */
      version: number;
    };
    /** ServicePage */
    ServicePage: {
      /** Items */
      items: components["schemas"]["ServiceOut"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ServiceUpdate */
    ServiceUpdate: {
      /** Default Estimated Hours */
      default_estimated_hours?: number | string | null;
      /** Description */
      description?: string | null;
      /** Name */
      name?: string | null;
      /** Price */
      price?: number | null;
      /** Price Fixed */
      price_fixed?: boolean | null;
      /** Vat Rate */
      vat_rate?: number | string | null;
      /** Version */
      version: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VersionRequest */
    VersionRequest: {
      /** Version */
      version: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  attachments_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attachment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  audit_events_list: {
    parameters: {
      query?: {
        entity_type?: components["schemas"]["EntityType"] | null;
        actor_id?: string | null;
        occurred_from?: string | null;
        occurred_to?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEventPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth_change_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — UNAUTHENTICATED: Vui lòng đăng nhập. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — VALIDATION_ERROR (current_password / new_password) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — ACCOUNT_LOCKED: Tài khoản tạm khoá do đăng nhập sai nhiều lần. Vui lòng thử lại sau 15 phút. */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description problem+json — INVALID_CREDENTIALS: Email hoặc mật khẩu không đúng. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — ACCOUNT_DISABLED: Tài khoản đã bị vô hiệu hoá. Vui lòng liên hệ quản lý. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** @description problem+json — ACCOUNT_LOCKED: Tài khoản tạm khoá do đăng nhập sai nhiều lần. Vui lòng thử lại sau 15 phút. */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description problem+json — UNAUTHENTICATED: Vui lòng đăng nhập. | SESSION_REVOKED: Phiên đăng nhập đã bị thu hồi. Vui lòng đăng nhập lại. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  employees_list: {
    parameters: {
      query?: {
        q?: string | null;
        role?: ("MANAGER" | "SALE" | "TECH_LEAD" | "TECHNICIAN") | null;
        is_active?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeWithPassword"];
        };
      };
      /** @description problem+json — CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_activate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_reset_password: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeWithPassword"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  employees_set_roles: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        employee_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RolesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmployeeOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | LAST_MANAGER | CANNOT_DEACTIVATE_SELF | INVALID_TRANSITION | CONFLICT (email) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  system_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Database unreachable (problem+json, code SERVICE_UNAVAILABLE) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description problem+json — UNAUTHENTICATED: Vui lòng đăng nhập. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — PASSWORD_CHANGE_REQUIRED | FORBIDDEN */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  products_list: {
    parameters: {
      query?: {
        q?: string | null;
        category?:
          | (
              | "PC"
              | "LAPTOP"
              | "MONITOR"
              | "PRINTER"
              | "SCANNER"
              | "PRINTER_SUPPLY"
              | "CAMERA"
              | "RECORDER"
              | "STORAGE"
              | "NETWORK"
              | "ACCESSORY"
              | "MATERIAL"
              | "SOFTWARE"
              | "OTHER"
            )
          | null;
        brand?: string | null;
        is_active?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  products_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description problem+json — CONFLICT (sku) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  products_import_commit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_products_import_commit"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportCommitResult"];
        };
      };
      /** @description problem+json — EMPTY_FILE|MISSING_COLUMNS|TOO_MANY_ROWS|INVALID_FILE|FILE_TOO_LARGE|IMPORT_HAS_ERRORS */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  products_import_preview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_products_import_preview"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportPreview"];
        };
      };
      /** @description problem+json — EMPTY_FILE | MISSING_COLUMNS | TOO_MANY_ROWS | INVALID_FILE | FILE_TOO_LARGE */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  products_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  products_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | CONFLICT (sku/code) | INVALID_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  products_activate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | CONFLICT (sku/code) | INVALID_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  products_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | CONFLICT (sku/code) | INVALID_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  products_upload_image: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_products_upload_image"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImageUploaded"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — INVALID_FILE_TYPE | FILE_TOO_LARGE | UNSUPPORTED_MEDIA_TYPE */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  services_list: {
    parameters: {
      query?: {
        q?: string | null;
        category?:
          | (
              | "INSTALLATION"
              | "REPAIR"
              | "MAINTENANCE"
              | "REFILL"
              | "SOFTWARE"
              | "NETWORK_CABLING"
              | "OTHER"
            )
          | null;
        unit?:
          | ("CAI" | "MAY" | "BO" | "MET" | "CUON" | "HOP" | "LICENSE" | "LAN" | "DIEM" | "GIO")
          | null;
        is_active?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServicePage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  services_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServiceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceOut"];
        };
      };
      /** @description problem+json — CONFLICT (code) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  services_import_commit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_services_import_commit"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportCommitResult"];
        };
      };
      /** @description problem+json — EMPTY_FILE|MISSING_COLUMNS|TOO_MANY_ROWS|INVALID_FILE|FILE_TOO_LARGE|IMPORT_HAS_ERRORS */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  services_import_preview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_services_import_preview"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportPreview"];
        };
      };
      /** @description problem+json — EMPTY_FILE | MISSING_COLUMNS | TOO_MANY_ROWS | INVALID_FILE | FILE_TOO_LARGE */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  services_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  services_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ServiceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | CONFLICT (sku/code) | INVALID_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  services_activate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | CONFLICT (sku/code) | INVALID_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  services_deactivate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VersionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceOut"];
        };
      };
      /** @description problem+json — NOT_FOUND */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description problem+json — STALE_VERSION | CONFLICT (sku/code) | INVALID_TRANSITION */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
