"""add_services

Revision ID: 15fc4f55e718
Revises: 43b1bcd57ad9
Create Date: 2026-09-28 04:23:39.345090+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "15fc4f55e718"
down_revision: str | None = "43b1bcd57ad9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), server_default=sa.text("8"), nullable=False),
        sa.Column("price_fixed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("default_estimated_hours", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IN ('INSTALLATION', 'REPAIR', 'MAINTENANCE', 'REFILL', 'SOFTWARE', "
            "'NETWORK_CABLING', 'OTHER')",
            name=op.f("ck_services_category"),
        ),
        sa.CheckConstraint(
            "unit IN ('CAI', 'MAY', 'BO', 'MET', 'CUON', 'HOP', 'LICENSE', 'LAN', 'DIEM', 'GIO')",
            name=op.f("ck_services_unit"),
        ),
        sa.CheckConstraint(
            "default_estimated_hours IS NULL OR default_estimated_hours >= 0",
            name=op.f("ck_services_default_estimated_hours_non_negative"),
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_services_price_non_negative")),
        sa.CheckConstraint("vat_rate >= 0 AND vat_rate <= 100", name=op.f("ck_services_vat_rate_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("code", name=op.f("uq_services_code")),
    )
    op.create_index(op.f("ix_services_category"), "services", ["category"], unique=False)
    op.create_index(op.f("ix_services_is_active"), "services", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_is_active"), table_name="services")
    op.drop_index(op.f("ix_services_category"), table_name="services")
    op.drop_table("services")
    # ### end Alembic commands ###
