"""attachments_revision_index

Revision ID: b2133c219133
Revises: d4a855d6cf3b
Create Date: 2026-10-08 02:43:50.205398+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b2133c219133"
down_revision: str | None = "d4a855d6cf3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_attachments_owner_kind_revision",
        "attachments",
        ["owner_type", "owner_id", "kind", "revision_no"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attachments_owner_kind_revision", table_name="attachments")
    # ### end Alembic commands ###
