"""add_tasks_and_assignments

Revision ID: d4a855d6cf3b
Revises: 408da919f89c
Create Date: 2026-10-01 18:41:58.335682+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d4a855d6cf3b"
down_revision: str | None = "408da919f89c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("created_in_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("estimated_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("cycle", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("order_line_ids", postgresql.ARRAY(sa.Uuid()), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("origin IN ('INITIAL', 'ADDITIONAL')", name=op.f("ck_tasks_origin")),
        sa.CheckConstraint("priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')", name=op.f("ck_tasks_priority")),
        sa.CheckConstraint(
            "status IN ('NEEDS_ASSIGNEE', 'PENDING_ACCEPTANCE', 'ACCEPTED', 'IN_PROGRESS', 'DONE', 'CANCELLED')",
            name=op.f("ck_tasks_status"),
        ),
        sa.ForeignKeyConstraint(["created_by"], ["employees.id"], name=op.f("fk_tasks_created_by_employees")),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_tasks_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("code", name=op.f("uq_tasks_code")),
    )
    op.create_index(op.f("ix_tasks_order_id"), "tasks", ["order_id"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column("reject_reason_code", sa.String(length=20), nullable=True),
        sa.Column("reject_reason_text", sa.Text(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_hours", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("completion_note", sa.Text(), nullable=True),
        sa.Column("assigned_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "reject_reason_code IS NULL OR reject_reason_code IN ('BUSY', 'SICK', 'SKILL', 'DISTANCE', 'OTHER')",
            name=op.f("ck_assignments_reject_reason_code"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'DONE', 'REMOVED')",
            name=op.f("ck_assignments_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"], ["employees.id"], name=op.f("fk_assignments_assigned_by_employees")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["employees.id"], name=op.f("fk_assignments_employee_id_employees")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_assignments_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
    )
    op.create_index(op.f("ix_assignments_employee_id"), "assignments", ["employee_id"], unique=False)
    op.create_index(op.f("ix_assignments_task_id"), "assignments", ["task_id"], unique=False)
    op.create_index(
        "uq_assignments_task_employee_cycle_active",
        "assignments",
        ["task_id", "employee_id", "cycle"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'DONE')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_assignments_task_employee_cycle_active",
        table_name="assignments",
        postgresql_where=sa.text("status IN ('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'DONE')"),
    )
    op.drop_index(op.f("ix_assignments_task_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_employee_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_tasks_order_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
