"""add_products_and_attachments

Revision ID: 43b1bcd57ad9
Revises: 20260927_0119
Create Date: 2026-09-27 14:04:25.644628+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "43b1bcd57ad9"
down_revision: str | None = "20260927_0119"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_type", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("revision_no", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["employees.id"], name=op.f("fk_attachments_uploaded_by_employees")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(op.f("ix_attachments_owner_id"), "attachments", ["owner_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("sku", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("brand", sa.String(length=60), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), server_default=sa.text("8"), nullable=False),
        sa.Column("price_fixed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("warranty_months", sa.SmallInteger(), nullable=True),
        sa.Column("specs", sa.Text(), nullable=True),
        sa.Column("image_attachment_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "category IN ('PC', 'LAPTOP', 'MONITOR', 'PRINTER', 'SCANNER', 'PRINTER_SUPPLY', 'CAMERA', "
            "'RECORDER', 'STORAGE', 'NETWORK', 'ACCESSORY', 'MATERIAL', 'SOFTWARE', 'OTHER')",
            name=op.f("ck_products_category"),
        ),
        sa.CheckConstraint(
            "unit IN ('CAI', 'MAY', 'BO', 'MET', 'CUON', 'HOP', 'LICENSE')", name=op.f("ck_products_unit")
        ),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_price_non_negative")),
        sa.CheckConstraint("vat_rate >= 0 AND vat_rate <= 100", name=op.f("ck_products_vat_rate_range")),
        sa.ForeignKeyConstraint(
            ["image_attachment_id"],
            ["attachments.id"],
            name=op.f("fk_products_image_attachment_id_attachments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index(op.f("ix_products_category"), "products", ["category"], unique=False)
    op.create_index(op.f("ix_products_is_active"), "products", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_products_image_attachment_id"), "products", ["image_attachment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_image_attachment_id"), table_name="products")
    op.drop_index(op.f("ix_products_is_active"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_attachments_owner_id"), table_name="attachments")
    op.drop_table("attachments")
    # ### end Alembic commands ###
