"""add_orders

Revision ID: 408da919f89c
Revises: 22afb850222f
Create Date: 2026-09-29 00:23:31.616029+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "408da919f89c"
down_revision: str | None = "22afb850222f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column("division", sa.String(length=30), nullable=True),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("customer_phone", sa.String(length=20), nullable=True),
        sa.Column("customer_email", sa.String(length=255), nullable=True),
        sa.Column("customer_tax_code", sa.String(length=20), nullable=True),
        sa.Column("service_address", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("work_description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("priority", sa.String(length=20), server_default=sa.text("'NORMAL'"), nullable=False),
        sa.Column("requested_date", sa.Date(), nullable=True),
        sa.Column("subtotal", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("discount_amount", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("vat_amount", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("total", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("payment_status", sa.String(length=20), server_default=sa.text("'UNPAID'"), nullable=False),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column("customer_feedback", sa.Text(), nullable=True),
        sa.Column("result_note", sa.Text(), nullable=True),
        sa.Column("confirmation_signer_name", sa.String(length=120), nullable=True),
        sa.Column("revision_no", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "payment_status IN ('UNPAID', 'PAID', 'PAY_LATER')", name=op.f("ck_orders_payment_status")
        ),
        sa.CheckConstraint(
            "priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')", name=op.f("ck_orders_priority")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PENDING_DISPATCH', 'IN_PROGRESS', 'AWAITING_CONFIRMATION', 'COMPLETED', 'REVISION', 'CANCELLED')",
            name=op.f("ck_orders_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["employees.id"], name=op.f("fk_orders_created_by_employees")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_orders_customer_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("code", name=op.f("uq_orders_code")),
    )
    op.create_index(op.f("ix_orders_created_by"), "orders", ["created_by"], unique=False)
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "order_lines",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("sku_snapshot", sa.String(length=40), nullable=True),
        sa.Column("name_snapshot", sa.String(length=255), nullable=False),
        sa.Column("unit_snapshot", sa.String(length=20), nullable=False),
        sa.Column("specs_snapshot", sa.Text(), nullable=True),
        sa.Column("warranty_months_snapshot", sa.SmallInteger(), nullable=True),
        sa.Column("catalog_price_snapshot", sa.BigInteger(), nullable=True),
        sa.Column("price_fixed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column("is_gift", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("line_discount", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("line_gross", sa.BigInteger(), nullable=False),
        sa.Column("line_vat", sa.BigInteger(), nullable=False),
        sa.Column("line_total", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "item_type IN ('PRODUCT', 'SERVICE', 'CUSTOM')", name=op.f("ck_order_lines_item_type")
        ),
        sa.CheckConstraint("line_discount >= 0", name=op.f("ck_order_lines_line_discount_non_negative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_lines_quantity_positive")),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_order_lines_unit_price_non_negative")),
        sa.CheckConstraint("vat_rate >= 0 AND vat_rate <= 100", name=op.f("ck_order_lines_vat_rate_range")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_lines_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_order_lines_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
    )
    op.create_index(op.f("ix_order_lines_order_id"), "order_lines", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_lines_order_id"), table_name="order_lines")
    op.drop_table("order_lines")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_by"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
