"""employees_code_sequences: code_sequences table, unaccent extension, employees(is_active) index (M1-04a)

Revision ID: 20260926_1407
Revises: 20260926_0551
Create Date: 2026-09-26 14:07:13.386503+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '20260926_1407'
down_revision: str | None = '20260926_0551'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Diacritic-insensitive employee search ("tuan" finds "Tuấn"). Kept on downgrade like citext.
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_sequences',
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'period', name=op.f('pk_code_sequences'))
    )
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_table('code_sequences')
    # ### end Alembic commands ###
